HF_MODEL_KEY = "hf_model"
PUSHED_SPACE_KEY = "pushed_space"
CUSTOM_CONFIG_KEY = "custom_config"

HF_SPACE_RELEASE_KEY = "HF_SPACE_RELEASE"

ACCESS_TOKEN_KEY = "ACCESS_TOKEN"

USERNAME_KEY = "USERNAME"
REPONAME_KEY = "REPONAME"

APP_PATH_KEY = "APP_PATH"
MODEL_HUB_REPO_PLACEHOLDER_KEY = "MODEL_HUB_REPO_PLACEHOLDER"
MODEL_HUB_URL_PLACEHOLDER_KEY = "MODEL_HUB_URL_PLACEHOLDER"
MODEL_VERSION_PLACEHOLDER_KEY = "MODEL_VERSION_PLACEHOLDER"
